# Generated by Django 4.2.3 on 2023-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('genres', models.CharField(max_length=200)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('year_release', models.IntegerField(blank=True, null=True)),
                ('metacritic_rating', models.CharField(max_length=200, null=True)),
                ('runtime', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
